'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Nizzie_s_Boutiquee.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _22398903_7c45_4ac1_ac2f_3d06885c70c8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("22398903-7c45-4ac1-ac2f-3d06885c70c8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _48fd387a_320f_4f62_8bae_18c38be64054() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("48fd387a-320f-4f62-8bae-18c38be64054", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4a528325_bc0c_40ca_b54e_e5ef79e20ce0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4a528325-bc0c-40ca-b54e-e5ef79e20ce0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4Pcs_Set_Europe_America_Vintage_Fashion_Multilayer_Beads___Gold() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4Pcs_Set Europe America Vintage Fashion Multilayer Beads - Gold", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5_9__Women_s_Sexy_High_Heels_Platforms_Pumps_Square_Toe_Chunky_Block_Heels_Rhinestone_Party_Shoes_Black_Satin_US6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5_9_ Women's Sexy High Heels Platforms Pumps Square Toe Chunky Block Heels Rhines"& _ 
                        "tone Party Shoes Black-Satin-US6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5pack_Letter_Tape_Panty_Set() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5pack Letter Tape Panty Set", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5pack_Letter_Tape_Panty_Set1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5pack Letter Tape Panty Set1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5pack_No_Show_Bra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5pack No Show Bra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6pairs_Solid_Crew_Socks_Women_Socks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6pairs Solid Crew Socks Women Socks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property adidas_Believe_This_2_0_Womens_Short_Running_Tights___Black___S() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adidas Believe This 2_0 Womens Short Running Tights - Black - S", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Advbridge_Women_Cargo_Mini_Skirt_Aesthetic_Y2k_90s_Low_Waist_Denim_Short_Skirt_Vintage_Harajuku_Streetwear_Slim_Sexy_Casual_Femme_Clothing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Advbridge Women Cargo Mini Skirt Aesthetic Y2k 90s Low Waist Denim Short Skirt Vi"& _ 
                        "ntage Harajuku Streetwear Slim Sexy Casual Femme Clothing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ami_Maternity___Nursing_Maxi_Dress___M___Navy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ami Maternity & Nursing Maxi Dress - M _ Navy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Artist_Couture_Supreme_Nudes_and_Pressed_Pigment_Eyeshadow_Palette_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Artist Couture Supreme Nudes and Pressed Pigment Eyeshadow Palette_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property avatar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("avatar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Betternotification_100__Cotton_Women_s_Soft_Pajama_Set_Full_Sleeve_Button_Shirt_crop_Top_shorts_3_Pieces_Matching_Set_Female_Loungewear_Streetwear_Rose_Red_S() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Betternotification 100% Cotton Women's Soft Pajama Set Full Sleeve Button Shirt+c"& _ 
                        "rop Top+shorts 3 Pieces Matching Set Female Loungewear Streetwear Rose Red-S", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Betternotification_2024_New_Women_s_Matching_Set_Sexy_Fluffy_Plush_Pajama_Sets_Hooded_Crop_Top_Shorts_Coat_Three_Pieces_Suit_Woman_Pyjama_Sleepwear_Color_1_S() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Betternotification 2024 New Women's Matching Set Sexy Fluffy Plush Pajama Sets Ho"& _ 
                        "oded Crop Top+Shorts+Coat Three Pieces Suit Woman Pyjama Sleepwear Color 1-S", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property brushes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brushes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property brushes1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brushes1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_Front_Drop_Shoulder_Cardigan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button Front Drop Shoulder Cardigan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Capture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Capture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ciing_2024_Spring_New_Flat_Women_Shoes_Loafers_Simple_Low_Heels_Office_Work_Casual_Shoes_Slip_on_Flat_Footwear_Ladies_Square_Toe_Shoes___black___37() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ciing 2024 Spring New Flat Women Shoes Loafers Simple Low Heels Office Work Casua"& _ 
                        "l Shoes Slip on Flat Footwear Ladies Square Toe Shoes - black _ 37", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Clothing_Accessories___Online_Clothing___Clothing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Clothing Accessories _ Online Clothing _ Clothing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property d41588dbb8a0074f0a21dc107d7c86ae() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("d41588dbb8a0074f0a21dc107d7c86ae", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dresses() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dresses", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Drop_Shoulder_Zipper_Puffer_Thick_Pockets_Coat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Drop Shoulder Zipper Puffer Thick Pockets Coat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property El_elegante_perfume_con_una_fragancia_embriagadora_que_dura_todo_el_día_y_levanta_el_ánimo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("El elegante perfume con una fragancia embriagadora que dura todo el día y levanta"& _ 
                        " el ánimo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f6c781c9056f1a7c88e37037f2b7bb1a() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f6c781c9056f1a7c88e37037f2b7bb1a", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fashionable_Outdoors_Slide_Sandals_for_Women__Buckle_Decor_Plain_Jelly_Open_Toe_Footbed_Sandals() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fashionable Outdoors Slide Sandals for Women, Buckle Decor Plain Jelly Open Toe F"& _ 
                        "ootbed Sandals", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fashionkova_Vintage_Gray_Oversize_Hoodies_Women_Harajuku_Hip_Hop_Embroidery_Loose_Sweatshirts_Long_Sleeve_Casual_Tops_Grunge_Korean() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fashionkova Vintage Gray Oversize Hoodies Women Harajuku Hip Hop Embroidery Loose"& _ 
                        " Sweatshirts Long Sleeve Casual Tops Grunge Korean", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FINETOO_Women_s_Boxer_Briefs_Summer_Safety_Short_Panties_Seamless_Anti_glare_Ladies_Pants_Girl_Cozy_Female_Underwear_M_XXL_color_1_M_1pc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FINETOO Women's Boxer Briefs Summer Safety Short Panties Seamless Anti-glare Ladi"& _ 
                        "es Pants Girl Cozy Female Underwear M-XXL color 1-M-1pc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FINETOO_Women_s_Cotton_Briefs_Sexy_Underwear_Women_s_Panties_Female_Underpants_Fashion_Ladies_Lingerie_Solid_Colors_M_XXL_Blue_XXL_1pc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FINETOO Women's Cotton Briefs Sexy Underwear Women's Panties Female Underpants Fa"& _ 
                        "shion Ladies Lingerie Solid Colors M-XXL Blue-XXL-1pc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Floral_Lace_Underwire_Garter_Lingerie_Set_With_1pair_Leg_Ring() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Floral Lace Underwire Garter Lingerie Set With 1pair Leg Ring", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Floral_Lace_Underwire_Garter_Lingerie_Set_With_Stockings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Floral Lace Underwire Garter Lingerie Set With Stockings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Floral_Lace_Underwire_Garter_Lingerie_Set_With_Stockings1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Floral Lace Underwire Garter Lingerie Set With Stockings1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Floral_Lace_Underwire_Garter_Lingerie_Set_With_Stockings2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Floral Lace Underwire Garter Lingerie Set With Stockings2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Free_People_Love_Letter_Cami() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Free People Love Letter Cami", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gingham_Backless_Crop_Top_With_Shorts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gingham Backless Crop Top With Shorts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grocery_store() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grocery-store", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hipster_Bikini_Bottoms_in_Sky_Blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hipster Bikini Bottoms in Sky Blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property home() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMG_7817() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_7817", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Isuijie_Women_s_Cotton_Print_Cartoon_Boxer_Briefs_Boyshort_Ladies_Breathable_Comfort_Elastic_Safety_Panties_Female_Underwear_Briefs_06_XL_1pc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Isuijie Women's Cotton Print Cartoon Boxer Briefs Boyshort Ladies Breathable Comf"& _ 
                        "ort Elastic Safety Panties Female Underwear Briefs 06-XL-1pc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Kids_EVRYDAY_Chicas_bajo_irregular_con_capucha_Camiseta___Shorts_con_top_de_tirantes___Multicolor___11_12Y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kids EVRYDAY Chicas bajo irregular con capucha Camiseta & Shorts con top de tiran"& _ 
                        "tes - Multicolor _ 11-12Y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Kindred_Bravely_Sienna_Smocked_Midi_Maternity_Nursing_Dress_in_Lilac_Stone_at_Nordstrom__Size_Small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kindred Bravely Sienna Smocked Midi Maternity_Nursing Dress in Lilac Stone at Nor"& _ 
                        "dstrom, Size Small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lianfudai_Suit_Hip_Hop_Punk_Ring_Men_Women_Jewelry_Party_Accessories_Ring_Personality_Three_Finger_Conjoined_Chain_Open_Ring_New_Trend___AE725() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lianfudai Suit Hip Hop Punk Ring Men Women Jewelry Party Accessories Ring Persona"& _ 
                        "lity Three Finger Conjoined Chain Open Ring New Trend - AE725", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property love() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("love", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Makeup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Makeup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Maternity_Elegant_Off_Shoulder_Long_Sleeve_Knitted_Bodycon_Dress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Maternity Elegant Off Shoulder Long Sleeve Knitted Bodycon Dress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Maternity_High_Waist_Solid_Skirt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Maternity High Waist Solid Skirt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Maternity_Solid_Cami_Bodycon_Dress_With_Coat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Maternity Solid Cami Bodycon Dress With Coat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Momyknows_Light_Blue_Backless_Fashion_Beach_Photoshoot_One_Piece_Maternity_Swimwear___Light_Blue___S() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Momyknows Light Blue Backless Fashion Beach Photoshoot One Piece Maternity Swimwe"& _ 
                        "ar - Light Blue _ S", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mulheres_1_peça_Bandana_padrão_paisley_fashionable_para_diário() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mulheres 1 peça Bandana padrão paisley fashionable para diário", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Multi_Pocket_Washed_Loose_Fit_Floor_Length_Jeans___Blue___L___No() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Multi-Pocket Washed Loose-Fit Floor-Length Jeans - Blue _ L _ No", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property New_sexy_three_dimensional_flower_slanted_shoulder_one_piece_swimsuit___Black___L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New sexy three-dimensional flower slanted shoulder one-piece swimsuit - Black _ L"& _ 
                        "", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Olivia_Mark___Elegantes_botas_de_invierno_para_mujer_con_puntera_redonda__detalle_de_piel_sintética_y_puño_de_piel_para_una_comodidad_y_un_estilo_definitivos___Marrón_café() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Olivia Mark - Elegantes botas de invierno para mujer con puntera redonda, detalle"& _ 
                        " de piel sintética y puño de piel para una comodidad y un estilo definitivos - M"& _ 
                        "arrón café", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Olivia_Mark___Kimono_boho_para_mujer__Kimono_de_playa_de_manga_larga_con_estampado_de_animales____multicolor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Olivia Mark - Kimono boho para mujer_ Kimono de playa de manga larga con estampad"& _ 
                        "o de animales_ - multicolor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Open_Front_Belted_Satin_Night_Robe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Open Front Belted Satin Night Robe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pearl_bow_necklace() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pearl bow necklace", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PHA_Fashion___VLN_Bags___512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PHA Fashion - VLN Bags - 512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pineapple_Print_Tee___Shorts_PJ_Set___Pajama_Set() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pineapple Print Tee & Shorts PJ Set _ Pajama Set", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Premium_Photo___Bags_retail_and_black_woman_with_a_credit_card_smartphone_or_ecommerce_on_a_grey_studio_background_Female_person_shopper_or_model_with_cellphone_boutique_items_or_purchase_w() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Premium Photo _ Bags retail and black woman with a credit card smartphone or ecom"& _ 
                        "merce on a grey studio background Female person shopper or model with cellphone "& _ 
                        "boutique items or purchase w", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ribbed_Zip_Up_Jumpsuit___Long_Sleeve___Black___S() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ribbed Zip-Up Jumpsuit - Long Sleeve - Black _ S", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Roupão_de_Banho___Feminino_Rosa_718___GG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Roupão de Banho - Feminino Rosa 718 _ GG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Satin_Lace_Pajamas_Set_Women_Strap_Top_Pants_Sleepwear_Sleep_Suit___Pink_Set___A___XL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Satin Lace Pajamas Set Women Strap Top Pants Sleepwear Sleep Suit - Pink Set - A "& _ 
                        "_ XL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Seamless_Over_the_Bump_Underwear___S___Beige() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Seamless Over the Bump Underwear - S _ Beige", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SHEIN_USA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SHEIN USA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shopping_bag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shopping-bag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Silk_Chunky_Square_Heel_Boots___Rosy_Red___35() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Silk Chunky Square Heel Boots - Rosy Red _ 35", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Silk_Chunky_Square_Heel_Boots___Rosy_Red___351() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Silk Chunky Square Heel Boots - Rosy Red _ 351", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property skin_care() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skin care", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Snatched_Eyes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Snatched Eyes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sneaker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sneaker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Square_Toe_Slingback_Flats() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Square Toe Slingback Flats", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sunnies() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sunnies", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Swimsuit___WHOLESALE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Swimsuit - WHOLESALE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tanguoant_Woman_Sneakers_Women_s_Shoes_Ladies_Casual_Breathable_Female_Vulcanized_Shoes_Lace_Up_Woman_Comfort_High_Top_Walking_Shoe_801_black_42() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tanguoant Woman Sneakers Women's Shoes Ladies Casual Breathable Female Vulcanized"& _ 
                        " Shoes Lace Up Woman Comfort High Top Walking Shoe 801 black-42", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Textured_Bikini_Set_Ruffle_Layered_Cami_Top___Ruffle_Skirt_2_Piece_Swimsuit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Textured Bikini Set Ruffle Layered Cami Top & Ruffle Skirt 2 Piece Swimsuit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property The_Best_Maternity_Bras_to_Get_You_Through_Your_Pregnancy__and_After_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("The Best Maternity Bras to Get You Through Your Pregnancy (and After)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tie_Side_Tanga_Bikini_Swimsuit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tie Side Tanga Bikini Swimsuit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tops() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tops", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ugg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ugg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Unique_Men_s_Watch_Date_Quartz_Display_With_2pcs_set_Bangle_Best_Gift_To_Male() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Unique Men's Watch Date Quartz Display With 2pcs_set Bangle Best Gift To Male", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WannaThis_Elegant_Folds_Women_Split_Knee_Dress_Sleeveless_Bodycon_Sexy_Fashion_Front_Vintage_Partywear_Night_Club_Tube_Dresses_Purple_M() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WannaThis Elegant Folds Women Split Knee Dress Sleeveless Bodycon Sexy Fashion Fr"& _ 
                        "ont Vintage Partywear Night Club Tube Dresses Purple-M", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Wavy_Chunky_Hoops_in_3_4_Silver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wavy Chunky Hoops in 3_4 Silver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Women_3pc_Suit_Custom_Made_Premium_Cotton_Long_Coat_Formal_Event_Wedding_Dinner_Cocktail_Bride_Prom_Party_Wear_Set_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Women 3pc Suit Custom Made Premium Cotton Long Coat Formal Event Wedding Dinner C"& _ 
                        "ocktail Bride Prom Party Wear Set_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Women_Fluffy_Plush_Thicken_Lapel_High_Low_Hem_Loungewear_Warm_Pajamas_Set___Grey___6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Women Fluffy Plush Thicken Lapel High Low Hem Loungewear Warm Pajamas Set - Grey "& _ 
                        "_ 6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Women_s___Men_s_Clothing__Shop_Online_Fashion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Women's & Men's Clothing, Shop Online Fashion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Women_s___Men_s_Clothing__Shop_Online_Fashion__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Women's & Men's Clothing, Shop Online Fashion (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Women_s___Men_s_Clothing__Shop_Online_Fashion__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Women's & Men's Clothing, Shop Online Fashion (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Women_s___Men_s_Clothing__Shop_Online_Fashion__4_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Women's & Men's Clothing, Shop Online Fashion (4)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Women_s_1_Piece_Lace___Sequins___Beaded_G_strings__Thongs_Panties___Normal_Low_Waist_White_Black_Blue_One_Size___Mesh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Women's 1 Piece Lace _ Sequins _ Beaded G-strings  Thongs Panties - Normal Low Wa"& _ 
                        "ist White Black Blue One-Size _ Mesh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Women_s_Boho_Wavy_Striped_Strappy_V_Neck_Bikini_Top___Cupshe_XL_Multicolored() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Women's Boho Wavy Striped Strappy V-Neck Bikini Top - Cupshe-XL-Multicolored", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Women_s_Denim_Shorts_Printed_Pocket_Casual_Women_s_Shorts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Women's Denim Shorts Printed Pocket Casual Women's Shorts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Women_s_Denim_Shorts_Printed_Pocket_Casual_Women_s_Shorts1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Women's Denim Shorts Printed Pocket Casual Women's Shorts1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Women_s_Striped_Print_Two_Pieces_Bikini_Swimsuit_Three_Piece_Swimwear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Women's Striped Print Two Pieces Bikini Swimsuit Three-Piece Swimwear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Womens_Linen_Button_Front_Batwing_Beach_Kaftan_Shirt___White___M() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Womens Linen Button Front Batwing Beach Kaftan Shirt - White - M", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Womens_Next_Diamond_Pattern_Bum__Tum_And_Thigh_Shaping_Tights____diamond_pattern() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Womens Next Diamond Pattern Bum, Tum And Thigh Shaping Tights -  diamond pattern", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
