'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Nizzie_s_Boutiquee.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5_9__Women_s_Sexy_High_Heels_Platforms_Pumps_Square_Toe_Chunky_Block_Heels_Rhinestone_Party_Shoes_Black_Satin_US6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5_9_ Women's Sexy High Heels Platforms Pumps Square Toe Chunky Block Heels Rhines"& _ 
                        "tone Party Shoes Black-Satin-US6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5pack_Letter_Tape_Panty_Set() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5pack Letter Tape Panty Set", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5pack_No_Show_Bra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5pack No Show Bra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6pairs_Solid_Crew_Socks_Women_Socks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6pairs Solid Crew Socks Women Socks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property adidas_Believe_This_2_0_Womens_Short_Running_Tights___Black___S() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adidas Believe This 2_0 Womens Short Running Tights - Black - S", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Advbridge_Women_Cargo_Mini_Skirt_Aesthetic_Y2k_90s_Low_Waist_Denim_Short_Skirt_Vintage_Harajuku_Streetwear_Slim_Sexy_Casual_Femme_Clothing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Advbridge Women Cargo Mini Skirt Aesthetic Y2k 90s Low Waist Denim Short Skirt Vi"& _ 
                        "ntage Harajuku Streetwear Slim Sexy Casual Femme Clothing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_Front_Drop_Shoulder_Cardigan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button Front Drop Shoulder Cardigan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Capture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Capture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ciing_2024_Spring_New_Flat_Women_Shoes_Loafers_Simple_Low_Heels_Office_Work_Casual_Shoes_Slip_on_Flat_Footwear_Ladies_Square_Toe_Shoes___black___37() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ciing 2024 Spring New Flat Women Shoes Loafers Simple Low Heels Office Work Casua"& _ 
                        "l Shoes Slip on Flat Footwear Ladies Square Toe Shoes - black _ 37", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dresses() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dresses", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Drop_Shoulder_Zipper_Puffer_Thick_Pockets_Coat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Drop Shoulder Zipper Puffer Thick Pockets Coat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f6c781c9056f1a7c88e37037f2b7bb1a() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f6c781c9056f1a7c88e37037f2b7bb1a", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fashionable_Outdoors_Slide_Sandals_for_Women__Buckle_Decor_Plain_Jelly_Open_Toe_Footbed_Sandals() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fashionable Outdoors Slide Sandals for Women, Buckle Decor Plain Jelly Open Toe F"& _ 
                        "ootbed Sandals", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fashionkova_Vintage_Gray_Oversize_Hoodies_Women_Harajuku_Hip_Hop_Embroidery_Loose_Sweatshirts_Long_Sleeve_Casual_Tops_Grunge_Korean() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fashionkova Vintage Gray Oversize Hoodies Women Harajuku Hip Hop Embroidery Loose"& _ 
                        " Sweatshirts Long Sleeve Casual Tops Grunge Korean", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FINETOO_Women_s_Boxer_Briefs_Summer_Safety_Short_Panties_Seamless_Anti_glare_Ladies_Pants_Girl_Cozy_Female_Underwear_M_XXL_color_1_M_1pc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FINETOO Women's Boxer Briefs Summer Safety Short Panties Seamless Anti-glare Ladi"& _ 
                        "es Pants Girl Cozy Female Underwear M-XXL color 1-M-1pc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FINETOO_Women_s_Cotton_Briefs_Sexy_Underwear_Women_s_Panties_Female_Underpants_Fashion_Ladies_Lingerie_Solid_Colors_M_XXL_Blue_XXL_1pc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FINETOO Women's Cotton Briefs Sexy Underwear Women's Panties Female Underpants Fa"& _ 
                        "shion Ladies Lingerie Solid Colors M-XXL Blue-XXL-1pc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Free_People_Love_Letter_Cami() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Free People Love Letter Cami", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gingham_Backless_Crop_Top_With_Shorts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gingham Backless Crop Top With Shorts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hipster_Bikini_Bottoms_in_Sky_Blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hipster Bikini Bottoms in Sky Blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMG_7817() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_7817", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Isuijie_Women_s_Cotton_Print_Cartoon_Boxer_Briefs_Boyshort_Ladies_Breathable_Comfort_Elastic_Safety_Panties_Female_Underwear_Briefs_06_XL_1pc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Isuijie Women's Cotton Print Cartoon Boxer Briefs Boyshort Ladies Breathable Comf"& _ 
                        "ort Elastic Safety Panties Female Underwear Briefs 06-XL-1pc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Momyknows_Light_Blue_Backless_Fashion_Beach_Photoshoot_One_Piece_Maternity_Swimwear___Light_Blue___S() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Momyknows Light Blue Backless Fashion Beach Photoshoot One Piece Maternity Swimwe"& _ 
                        "ar - Light Blue _ S", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Multi_Pocket_Washed_Loose_Fit_Floor_Length_Jeans___Blue___L___No() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Multi-Pocket Washed Loose-Fit Floor-Length Jeans - Blue _ L _ No", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property New_sexy_three_dimensional_flower_slanted_shoulder_one_piece_swimsuit___Black___L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New sexy three-dimensional flower slanted shoulder one-piece swimsuit - Black _ L"& _ 
                        "", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Olivia_Mark___Elegantes_botas_de_invierno_para_mujer_con_puntera_redonda__detalle_de_piel_sintética_y_puño_de_piel_para_una_comodidad_y_un_estilo_definitivos___Marrón_café() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Olivia Mark - Elegantes botas de invierno para mujer con puntera redonda, detalle"& _ 
                        " de piel sintética y puño de piel para una comodidad y un estilo definitivos - M"& _ 
                        "arrón café", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Olivia_Mark___Kimono_boho_para_mujer__Kimono_de_playa_de_manga_larga_con_estampado_de_animales____multicolor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Olivia Mark - Kimono boho para mujer_ Kimono de playa de manga larga con estampad"& _ 
                        "o de animales_ - multicolor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ribbed_Zip_Up_Jumpsuit___Long_Sleeve___Black___S() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ribbed Zip-Up Jumpsuit - Long Sleeve - Black _ S", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Silk_Chunky_Square_Heel_Boots___Rosy_Red___35() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Silk Chunky Square Heel Boots - Rosy Red _ 35", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sneaker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sneaker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Square_Toe_Slingback_Flats() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Square Toe Slingback Flats", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Textured_Bikini_Set_Ruffle_Layered_Cami_Top___Ruffle_Skirt_2_Piece_Swimsuit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Textured Bikini Set Ruffle Layered Cami Top & Ruffle Skirt 2 Piece Swimsuit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tie_Side_Tanga_Bikini_Swimsuit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tie Side Tanga Bikini Swimsuit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ugg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ugg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WannaThis_Elegant_Folds_Women_Split_Knee_Dress_Sleeveless_Bodycon_Sexy_Fashion_Front_Vintage_Partywear_Night_Club_Tube_Dresses_Purple_M() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WannaThis Elegant Folds Women Split Knee Dress Sleeveless Bodycon Sexy Fashion Fr"& _ 
                        "ont Vintage Partywear Night Club Tube Dresses Purple-M", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Women_3pc_Suit_Custom_Made_Premium_Cotton_Long_Coat_Formal_Event_Wedding_Dinner_Cocktail_Bride_Prom_Party_Wear_Set_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Women 3pc Suit Custom Made Premium Cotton Long Coat Formal Event Wedding Dinner C"& _ 
                        "ocktail Bride Prom Party Wear Set_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Women_s___Men_s_Clothing__Shop_Online_Fashion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Women's & Men's Clothing, Shop Online Fashion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Women_s___Men_s_Clothing__Shop_Online_Fashion__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Women's & Men's Clothing, Shop Online Fashion (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Women_s_1_Piece_Lace___Sequins___Beaded_G_strings__Thongs_Panties___Normal_Low_Waist_White_Black_Blue_One_Size___Mesh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Women's 1 Piece Lace _ Sequins _ Beaded G-strings  Thongs Panties - Normal Low Wa"& _ 
                        "ist White Black Blue One-Size _ Mesh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Women_s_Boho_Wavy_Striped_Strappy_V_Neck_Bikini_Top___Cupshe_XL_Multicolored() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Women's Boho Wavy Striped Strappy V-Neck Bikini Top - Cupshe-XL-Multicolored", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Women_s_Denim_Shorts_Printed_Pocket_Casual_Women_s_Shorts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Women's Denim Shorts Printed Pocket Casual Women's Shorts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Women_s_Denim_Shorts_Printed_Pocket_Casual_Women_s_Shorts1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Women's Denim Shorts Printed Pocket Casual Women's Shorts1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Women_s_Striped_Print_Two_Pieces_Bikini_Swimsuit_Three_Piece_Swimwear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Women's Striped Print Two Pieces Bikini Swimsuit Three-Piece Swimwear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Womens_Linen_Button_Front_Batwing_Beach_Kaftan_Shirt___White___M() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Womens Linen Button Front Batwing Beach Kaftan Shirt - White - M", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Womens_Next_Diamond_Pattern_Bum__Tum_And_Thigh_Shaping_Tights____diamond_pattern() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Womens Next Diamond Pattern Bum, Tum And Thigh Shaping Tights -  diamond pattern", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
